### ISSUE TITLE
Adding RMB menu to the GUI mode

### ISSUE THREAD

**Issue by kas1e** [capehill/glsnoop#17]
To fullfill GUI mode more, will be nice to add "menu" item which spawn when user press RMB (right mouse button). Currently it can be just "About, Quit, Iconify" as initiall version, and later it can be expand more when there will be any needs for.

**Comment by samo79** [comment]
In gui.c

{ NM_ITEM, "About", "?", 0, 0, (APTR)MID_About },

In the "About" menu option you might add the ... (3 points)  at the end

**Comment by kas1e** [comment]
@capehill 
If you want to loose some time on cosmetic things, and didn't bother with nitpicking, then to make it all feels "in style with os4", then "About" window need to be centered on screen and there should be button "ok" by pressing on which it closes the same as if you press on close gadget. Also there should be an image with "!" at left.

As example of it can be seen "About" from console, or "About" of workbench, or "About" of any prefs (like screenmode prefs).

No that its anyhow important, but just to make all perfect, if you want to spend some time on those unimportant things :)

**Comment by capehill** [comment]
@kas1e 
Do you know how to create the ! image?

**Comment by kas1e** [comment]
@capehill 
Yeah, sure, there is :

```
// gcc error_window.c -lauto


#define __USE_INLINE__ 1

#include <proto/intuition.h>
#include <classes/requester.h>
#include <reaction/reaction_macros.h>


Object               *win_obj;
Object               *requester_object;
uint32                result = 0;


int main()
{

                 requester_object = NewObject(NULL, "requester.class",
                              REQ_Type,  REQTYPE_INFO,
                              REQ_Image, REQIMAGE_INFO,
                              REQ_TitleText,  "Info window",
                              REQ_BodyText,   "There is some tasty information",
                              REQ_GadgetText, "OK",
                    TAG_END);
                 
                  SetAttrs(win_obj, WA_BusyPointer, TRUE, TAG_DONE);
                  result = IDoMethod(requester_object, RM_OPENREQ, NULL, NULL, /*window,*/ NULL, TAG_DONE);
                  DisposeObject(requester_object);
                  requester_object = NULL;
                  SetAttrs(win_obj, WA_BusyPointer, FALSE, TAG_DONE);
}

```

As far as i know is the "most system way" of how it done everywhere in system. Also that window will be already centered for you. You also can use such code for "error" requesters for example, just REQIMAGE_INFO will be REQIMAGE_ERROR.

**Comment by capehill** [comment]
Thanks, that should simplify the code greatly. I was looking at the SDK GUI menu examples yesterday but their "About" item did nothing.

**Comment by kas1e** [comment]
That one done, thanks !
