### ISSUE TITLE
Translate all enum values during tracing 

### ISSUE THREAD

**Issue by capehill** [capehill/glsnoop#20]

**Comment by kas1e** [comment]
As we discuss on amigans.net, work on that ticket can be started about texture params.

We also need not forget also "EXT" ones. For example something like "34046" mean "GL_TEXTURE_MAX_ANISOTROPY_EXT" (which just didn't coverted in pure gles2.0 specs , but in extensions ones).

**Comment by capehill** [comment]
Done.
